### ISSUE TITLE
Get agent from environment

### ISSUE THREAD

**Issue by PaulPrice** [liximomo/vscode-remote-fs#29]
There is a configuration option to specify an agent (thanks!), but it appears to require a hardcoded path to the socket, which may change after restarting the agent. However, the agent socket is usually available in the `SSH_AUTH_SOCK` environment variable.

Please add an option to retrieve the path to the agent socket from the environment.

**Comment by liximomo** [comment]
Already supported.

```
"agent": "$SSH_AUTH_SOCK"
```

**Comment by PaulPrice** [comment]
Begging your pardon, but that doesn't work. Here's the log:

```
[trace] stat /.vscode
[error] Error: connect ENOENT $SSH_AUTH_SOCK
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[trace] stat /
[error] Error: connect ENOENT $SSH_AUTH_SOCK
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[trace] stat /
[error] Error: connect ENOENT $SSH_AUTH_SOCK
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[trace] stat /
[error] Error: connect ENOENT $SSH_AUTH_SOCK
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[trace] stat /
[error] Error: connect ENOENT $SSH_AUTH_SOCK
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```

**Comment by liximomo** [comment]
Sorry. Coming soon.

**Comment by gt945** [comment]
Need this feature too, hope you can implement it ASAP

**Comment by diego898** [comment]
Bump!
