### ISSUE TITLE
Timed out while waiting for handshake

### ISSUE THREAD

**Issue by aderchox** [liximomo/vscode-remote-fs#77]
This is my configuration for this extension which I have added at the end of my settings.json file:
```
    // remotefs
    "remotefs.remote": {
      "dev": {
        "scheme": "ftp",
        "host": "myhostname.com",
        "username": "myusername",
        "rootPath": "/public_html/wordpress/wp-content/themes"
      }
    }
```
then I ctrl-shift-p and choose the "remote fs: add directory to workspace" option and it asks me to choose a remote and I choose it (myhostname.com:21) and it start loading and then asks for my password, I enter the password correctly (tested by other ftp softwares) but then it asks for the password once again, and if I enter it, it will ask again and so on. Meanwhile, a popup error is shown at the bottom right part of the vscode, which says: "Timed out while waiting for handshake"

**Desktop (please complete the following information):**
 - OS: Win
 - VSCode Version 1.42.1
 - Extension Version 0.0.15 (filled by looking at the changelog)

**Extension Logs**

> [trace] stat /
> [error] Error: Timed out while waiting for handshake
>     at Timeout._onTimeout (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\ssh2\lib\client.js:690:19)
>     at listOnTimeout (internal/timers.js:531:17)
>     at processTimers (internal/timers.js:475:7)
> [trace] stat /
> [error] Error: Timed out while waiting for handshake
>     at Timeout._onTimeout (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\ssh2\lib\client.js:690:19)
>     at listOnTimeout (internal/timers.js:531:17)
>     at processTimers (internal/timers.js:475:7)
> [trace] stat /
> [error] Error: 530 Login authentication failed
>     at Ftp.parse (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\jsftp\lib\jsftp.js:223:11)
>     at Ftp.parseResponse (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\jsftp\lib\jsftp.js:146:8)
>     at Stream.<anonymous> (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\jsftp\lib\jsftp.js:112:10)
>     at Stream.emit (events.js:200:13)
>     at ResponseParser.reemit (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\duplexer\index.js:70:25)
>     at ResponseParser.emit (events.js:200:13)
>     at readableAddChunk (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_readable.js:195:16)
>     at ResponseParser.Readable.push (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_readable.js:162:10)
>     at ResponseParser.Transform.push (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_transform.js:145:32)
>     at ResponseParser.<anonymous> (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\ftp-response-parser\index.js:62:12)
>     at Array.forEach (<anonymous>)
>     at ResponseParser._transform (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\ftp-response-parser\index.js:45:9)
>     at ResponseParser.Transform._read (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_transform.js:184:10)
>     at ResponseParser.Transform._write (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_transform.js:172:12)
>     at doWrite (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_writable.js:279:12)
>     at writeOrBuffer (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_writable.js:266:5)
>     at ResponseParser.Writable.write (c:\Users\USER\.vscode\extensions\liximomo.remotefs-0.0.16\node_modules\ftp-response-parser\node_modules\readable-stream\lib\_stream_writable.js:211:11)
>     at Socket.ondata (_stream_readable.js:713:22)
>     at Socket.emit (events.js:200:13)
>     at addChunk (_stream_readable.js:294:12)
>     at readableAddChunk (_stream_readable.js:275:11)
>     at Socket.Readable.push (_stream_readable.js:210:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
> 
>

**Comment by segalws** [comment]
try "connectTimeout": "50000"
